title: bearsworld
description: for friendbear GitHub Pages.
show_downloads: false
google_analytics: UA-37353976-2
twitter: true
hubspot: true
theme: jekyll-theme-architect
#paginate: 5
#paginate_path: "/blog/page:num/"
permalink: /:categories/:year/:month/:day/:title:output_ext
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: friendbear

comments: true

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - 'jekyll-feed'
  - 'jekyll-seo-tag'
  - 'jekyll-twitter-plugin'
